baseURL = 'https://brandoncruz.dev/'
languageCode = 'en-us'
title = 'Brandon Cruz'
theme = "maverick"
pagination.pagerSize = 5

[permalinks]
  pages = "/:slug"

[params]
  description = "A technology blog about DevSecOps tips and tutorials by Brandon Cruz."
  author = 'Brandon Cruz'

    [params.comments]
    enabled = false
    githubRepo = 'canhtran/maverick'
    theme = 'github-light'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    identifier = "resume"
    name = "Resume"
    url = "https://resume.brandoncruz.dev/"

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]
